{% set name = "scanpdf" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scanpdf-{{ version }}.tar.gz
  sha256: 2f7d64d4a9ea0bffbe0946bc03011d2305904e74658f4987723eaac08bd1bf20
  patches:
    - python3.patch

build:
  entry_points:
    - scanpdf = scanpdf.scanpdf:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - docopt >=0.6.1
    - python >={{ python_min }}
    - imagemagick
    - ghostscript
    - sane
    - identify

test:
  imports:
    - scanpdf
  commands:
    - pip check
    - scanpdf --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/virantha/scanpdf
  summary: Utility to use SANE/scanadf to scan to PDF
  license: Apache-2.0
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
